import daisyui from 'daisyui';

/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,vue}'],
    theme: {
        extend: {
            screens: {
                sm: '481px',
                md: '769px',
                lg: '1280px',
            },
            padding: {
                'container-xs': 'var(--ds-space-container-padding-xs)',
                'container-sm': 'var(--ds-space-container-padding-sm)',
                'container-md': 'var(--ds-space-container-padding-md)',
                'container-lg': 'var(--ds-space-container-padding-lg)',
                'container-xl': 'var(--ds-space-container-padding-xl)',
                'interactive-xs': 'var(--ds-space-interactive-padding-xs)',
                'interactive-sm': 'var(--ds-space-interactive-padding-sm)',
                'interactive-md': 'var(--ds-space-interactive-padding-md)',
                'interactive-lg': 'var(--ds-space-interactive-padding-lg)',
                'interactive-xl': 'var(--ds-space-interactive-padding-xl)',
            },
            gap: {
                'container-xs': 'var(--ds-space-container-gap-xs)',
                'container-sm': 'var(--ds-space-container-gap-sm)',
                'container-md': 'var(--ds-space-container-gap-md)',
                'container-lg': 'var(--ds-space-container-gap-lg)',
                'container-xl': 'var(--ds-space-container-gap-xl)',
                'interactive-xs': 'var(--ds-space-interactive-gap-xs)',
                'interactive-sm': 'var(--ds-space-interactive-gap-sm)',
                'interactive-md': 'var(--ds-space-interactive-gap-md)',
                'interactive-lg': 'var(--ds-space-interactive-gap-lg)',
                'interactive-xl': 'var(--ds-space-interactive-gap-xl)',
            },
            borderWidth: {
                hairline: 'var(--ds-border-width-hairline)',
                default: 'var(--ds-border-width-default)',
                thick: 'var(--ds-border-width-thick)',
                heavy: 'var(--ds-border-width-heavy)',
            },
            borderRadius: {
                'container-xs': 'var(--ds-shape-container-radius-xs)',
                'container-sm': 'var(--ds-shape-container-radius-sm)',
                'container-md': 'var(--ds-shape-container-radius-md)',
                'container-lg': 'var(--ds-shape-container-radius-lg)',
                'container-xl': 'var(--ds-shape-container-radius-xl)',
                'interactive-xs': 'var(--ds-shape-interactive-radius-xs)',
                'interactive-sm': 'var(--ds-shape-interactive-radius-sm)',
                'interactive-md': 'var(--ds-shape-interactive-radius-md)',
                'interactive-lg': 'var(--ds-shape-interactive-radius-lg)',
                'interactive-xl': 'var(--ds-shape-interactive-radius-xl)',
            },
            colors: {
                brand: 'var(--ds-color-brand)',
                'brand-focus': 'var(--ds-color-brand-focus)',
                'brand-content': 'var(--ds-color-brand-content)',
                'brand-soft': 'var(--ds-color-brand-soft)',
                secondary: 'var(--ds-color-secondary)',
                'secondary-focus': 'var(--ds-color-secondary-focus)',
                'secondary-content': 'var(--ds-color-secondary-content)',
                'secondary-soft': 'var(--ds-color-secondary-soft)',
                accent: 'var(--ds-color-accent)',
                'accent-focus': 'var(--ds-color-accent-focus)',
                'accent-content': 'var(--ds-color-accent-content)',
                'accent-soft': 'var(--ds-color-accent-soft)',
                neutral: 'var(--ds-color-neutral)',
                'neutral-focus': 'var(--ds-color-neutral-focus)',
                'neutral-content': 'var(--ds-color-neutral-content)',
                'neutral-soft': 'var(--ds-color-neutral-soft)',
                info: 'var(--ds-color-info)',
                'info-focus': 'var(--ds-color-info-focus)',
                'info-content': 'var(--ds-color-info-content)',
                'info-soft': 'var(--ds-color-info-soft)',
                success: 'var(--ds-color-success)',
                'success-focus': 'var(--ds-color-success-focus)',
                'success-content': 'var(--ds-color-success-content)',
                'success-soft': 'var(--ds-color-success-soft)',
                warning: 'var(--ds-color-warning)',
                'warning-focus': 'var(--ds-color-warning-focus)',
                'warning-content': 'var(--ds-color-warning-content)',
                'warning-soft': 'var(--ds-color-warning-soft)',
                error: 'var(--ds-color-error)',
                'error-focus': 'var(--ds-color-error-focus)',
                'error-content': 'var(--ds-color-error-content)',
                'error-soft': 'var(--ds-color-error-soft)',
            },
        },
    },
    plugins: [daisyui],
};
